# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.48.0"

default_platform :ios

certPath    = './Certificates/'
appId       = 'io.x8.flsetup'
appName     = 'flsetup'
language    = 'English'
teamName    = 'X8 Ltd'
sku         = '123abc'
appVersion  = '0.1'

platform :ios do

  desc "Creating an app, code signing certificate and provisioning profiles"

  lane :setup_provision do
    produce(
    app_identifier: appId,
    app_name:       appName,
    language:       language,
    app_version:    appVersion,
    sku:            sku,
    team_name:      teamName,
    skip_itc:       true
    )
    produce(
    username:       'krodak@x8.io',
    app_identifier: appId,
    app_name:       appName,
    language:       language,
    app_version:    appVersion,
    sku:            sku,
    team_name:      teamName,
    skip_devcenter: true
    )
    cert(output_path: certPath)
    cert(development: true, output_path: certPath)
    sigh(development: true, output_path: certPath)
    sigh(adhoc: true, output_path: certPath)
    sigh(force: true, output_path: certPath)
  end

  error do |lane, exception|

  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
